<?
$config = array
(	'fields' => array
	(
		'id' => array
		(
			'Field' => 'id',
			'Type' => 'int(10) unsigned',
			'Null' => 'NO',
			'Key' => 'PRI',
			'Default' => NULL,
			'Extra' => 'auto_increment',
		),
		'show_id' => array
		(
			'Field' => 'show_id',
			'Type' => 'varchar(16)',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'pid' => array
		(
			'Field' => 'pid',
			'Type' => 'int(10) unsigned',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'usr' => array
		(
			'Field' => 'usr',
			'Type' => 'varchar(255)',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'pwd' => array
		(
			'Field' => 'pwd',
			'Type' => 'varchar(255)',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'name' => array
		(
			'Field' => 'name',
			'Type' => 'text',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'email' => array
		(
			'Field' => 'email',
			'Type' => 'varchar(255)',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'tel' => array
		(
			'Field' => 'tel',
			'Type' => 'varchar(40)',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'fax' => array
		(
			'Field' => 'fax',
			'Type' => 'varchar(40)',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'street' => array
		(
			'Field' => 'street',
			'Type' => 'varchar(255)',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'num' => array
		(
			'Field' => 'num',
			'Type' => 'varchar(10)',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'zip' => array
		(
			'Field' => 'zip',
			'Type' => 'varchar(10)',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'city' => array
		(
			'Field' => 'city',
			'Type' => 'varchar(255)',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'country' => array
		(
			'Field' => 'country',
			'Type' => 'char(2)',
			'Null' => 'NO',
			'Key' => '',
			'Default' => 'de',
			'Extra' => '',
		),
		'lang' => array
		(
			'Field' => 'lang',
			'Type' => 'tinyint(2)',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'lang_default' => array
		(
			'Field' => 'lang_default',
			'Type' => 'tinyint(1)',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'type' => array
		(
			'Field' => 'type',
			'Type' => 'tinyint(1)',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'register_key' => array
		(
			'Field' => 'register_key',
			'Type' => 'varchar(64)',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'accept' => array
		(
			'Field' => 'accept',
			'Type' => 'tinyint(1)',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'sys_trashcan' => array
		(
			'Field' => 'sys_trashcan',
			'Type' => 'smallint(1) unsigned',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'sys_date_created' => array
		(
			'Field' => 'sys_date_created',
			'Type' => 'int(10) unsigned',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'sys_date_changed' => array
		(
			'Field' => 'sys_date_changed',
			'Type' => 'int(10) unsigned',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'sys_date_lastlogin' => array
		(
			'Field' => 'sys_date_lastlogin',
			'Type' => 'int(11)',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
	),
	'keys' => array
	(
		'0' => array
		(
			'type' => 'PRIMARY KEY',
			'fields' => array
			(
				'0' => 'id',
			),
		),
	),
	'data' => array
	(
		'0' => array
		(
			'id' => '122',
			'show_id' => '122',
			'pid' => '348',
			'usr' => 'root',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => '',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'AF',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '0',
			'sys_trashcan' => '0',
			'sys_date_created' => '0',
			'sys_date_changed' => '1147172573',
			'sys_date_lastlogin' => '1265383859',
		),
		'1' => array
		(
			'id' => '200',
			'show_id' => '200',
			'pid' => '357',
			'usr' => 'guest',
			'pwd' => 'a6d414ac4f293187dd042025834925f7',
			'name' => '',
			'email' => '',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'DE',
			'lang' => '1',
			'lang_default' => '1',
			'type' => '0',
			'register_key' => '',
			'accept' => '0',
			'sys_trashcan' => '0',
			'sys_date_created' => '1126541294',
			'sys_date_changed' => '1265383381',
			'sys_date_lastlogin' => '0',
		),
		'2' => array
		(
			'id' => '201',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'test',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'test@test.de',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1352670991',
			'sys_date_changed' => '1352670991',
			'sys_date_lastlogin' => '0',
		),
		'3' => array
		(
			'id' => '202',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'test2',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'test2@test.de',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1352671035',
			'sys_date_changed' => '1352671035',
			'sys_date_lastlogin' => '0',
		),
		'4' => array
		(
			'id' => '203',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'test3',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'test3@test.de',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1352671107',
			'sys_date_changed' => '1352671107',
			'sys_date_lastlogin' => '0',
		),
		'5' => array
		(
			'id' => '204',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'test4',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'test4@test.de',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1352671143',
			'sys_date_changed' => '1352671143',
			'sys_date_lastlogin' => '0',
		),
		'6' => array
		(
			'id' => '205',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'test5',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'test5@test.de',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1352671274',
			'sys_date_changed' => '1352671274',
			'sys_date_lastlogin' => '0',
		),
		'7' => array
		(
			'id' => '206',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'test6',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'test6@test.de',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1352671325',
			'sys_date_changed' => '1352671325',
			'sys_date_lastlogin' => '0',
		),
		'8' => array
		(
			'id' => '207',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'test7',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'test7@test.de',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1352671551',
			'sys_date_changed' => '1352671551',
			'sys_date_lastlogin' => '0',
		),
		'9' => array
		(
			'id' => '208',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'test8',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'test8@test.de',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1352671766',
			'sys_date_changed' => '1352671766',
			'sys_date_lastlogin' => '0',
		),
		'10' => array
		(
			'id' => '209',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'groovekugel',
			'pwd' => 'dbf2641b360d20ed942a79b59d0cd5bd',
			'name' => '',
			'email' => 'groovekugel@hotoshi.com',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1352671864',
			'sys_date_changed' => '1352671864',
			'sys_date_lastlogin' => '0',
		),
		'11' => array
		(
			'id' => '210',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'test9',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'test9@test.de',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1352707451',
			'sys_date_changed' => '1352707451',
			'sys_date_lastlogin' => '0',
		),
		'12' => array
		(
			'id' => '211',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'test11',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'test11@test.de',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1353249462',
			'sys_date_changed' => '1353249462',
			'sys_date_lastlogin' => '0',
		),
		'13' => array
		(
			'id' => '212',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'test13',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'test13@hotoshi.com',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1353255222',
			'sys_date_changed' => '1353255222',
			'sys_date_lastlogin' => '0',
		),
		'14' => array
		(
			'id' => '213',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'test14',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'test14@hotoshi.com',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1353255378',
			'sys_date_changed' => '1353255378',
			'sys_date_lastlogin' => '0',
		),
		'15' => array
		(
			'id' => '214',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'test15',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'test15@hotoshi.com',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1353255565',
			'sys_date_changed' => '1353255565',
			'sys_date_lastlogin' => '0',
		),
		'16' => array
		(
			'id' => '215',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'grannynanny1',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'grannynanny1@hotoshi.com',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1353256546',
			'sys_date_changed' => '1353256546',
			'sys_date_lastlogin' => '0',
		),
		'17' => array
		(
			'id' => '216',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'grannynanny2',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'grannynanny2@hotoshi.com',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1353256633',
			'sys_date_changed' => '1353256633',
			'sys_date_lastlogin' => '0',
		),
		'18' => array
		(
			'id' => '217',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'grannynanny3',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'grannynanny3@hotoshi.com',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1353256762',
			'sys_date_changed' => '1353256762',
			'sys_date_lastlogin' => '0',
		),
		'19' => array
		(
			'id' => '218',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'grannynanny4',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'grannynanny4@hotoshi.com',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1353256884',
			'sys_date_changed' => '1353256884',
			'sys_date_lastlogin' => '0',
		),
		'20' => array
		(
			'id' => '219',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'grannynanny5',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'grannynanny5@hotoshi.com',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1353257011',
			'sys_date_changed' => '1353257011',
			'sys_date_lastlogin' => '0',
		),
		'21' => array
		(
			'id' => '220',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'grannynanny6',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'grannynanny@hotoshi.com',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1353257162',
			'sys_date_changed' => '1353257162',
			'sys_date_lastlogin' => '0',
		),
		'22' => array
		(
			'id' => '221',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'pedro',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'pedro@tajapa.com',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1353257242',
			'sys_date_changed' => '1353257242',
			'sys_date_lastlogin' => '0',
		),
		'23' => array
		(
			'id' => '222',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'grannynanny7',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'grannynanny7@hotoshi.com',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1353258815',
			'sys_date_changed' => '1353258815',
			'sys_date_lastlogin' => '0',
		),
		'24' => array
		(
			'id' => '223',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'grannynanny8',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'grannynanny8@hotoshi.com',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1353263377',
			'sys_date_changed' => '1353263377',
			'sys_date_lastlogin' => '0',
		),
		'25' => array
		(
			'id' => '224',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'testa',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'testa@test.de',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1357390439',
			'sys_date_changed' => '1357390439',
			'sys_date_lastlogin' => '0',
		),
		'26' => array
		(
			'id' => '225',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'testb',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'testb@test.de',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1357390624',
			'sys_date_changed' => '1357390624',
			'sys_date_lastlogin' => '0',
		),
		'27' => array
		(
			'id' => '226',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'testc',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'testc@test.de',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1357390669',
			'sys_date_changed' => '1357390669',
			'sys_date_lastlogin' => '0',
		),
		'28' => array
		(
			'id' => '227',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'testd',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'testd@test.de',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1357390884',
			'sys_date_changed' => '1357390884',
			'sys_date_lastlogin' => '0',
		),
		'29' => array
		(
			'id' => '228',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'teste',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'teste@test.de',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1357391091',
			'sys_date_changed' => '1357391091',
			'sys_date_lastlogin' => '0',
		),
		'30' => array
		(
			'id' => '229',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'testf',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'testf@test.de',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1357391138',
			'sys_date_changed' => '1357391138',
			'sys_date_lastlogin' => '0',
		),
		'31' => array
		(
			'id' => '230',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'testg',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'testg@test.de',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1357391199',
			'sys_date_changed' => '1357391199',
			'sys_date_lastlogin' => '0',
		),
		'32' => array
		(
			'id' => '231',
			'show_id' => '',
			'pid' => '0',
			'usr' => 'testh',
			'pwd' => '098f6bcd4621d373cade4e832627b4f6',
			'name' => '',
			'email' => 'testh@test.de',
			'tel' => '',
			'fax' => '',
			'street' => '',
			'num' => '',
			'zip' => '',
			'city' => '',
			'country' => 'de',
			'lang' => '1',
			'lang_default' => '0',
			'type' => '0',
			'register_key' => '',
			'accept' => '1',
			'sys_trashcan' => '0',
			'sys_date_created' => '1357391336',
			'sys_date_changed' => '1357391336',
			'sys_date_lastlogin' => '0',
		),
	),

);
?>