<?
$config = array
(	'fields' => array
	(
		'id' => array
		(
			'Field' => 'id',
			'Type' => 'int(10) unsigned',
			'Null' => 'NO',
			'Key' => 'PRI',
			'Default' => NULL,
			'Extra' => 'auto_increment',
		),
		'name' => array
		(
			'Field' => 'name',
			'Type' => 'varchar(255)',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'url' => array
		(
			'Field' => 'url',
			'Type' => 'text',
			'Null' => 'YES',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'title' => array
		(
			'Field' => 'title',
			'Type' => 'varchar(255)',
			'Null' => 'YES',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'description' => array
		(
			'Field' => 'description',
			'Type' => 'text',
			'Null' => 'YES',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'keywords' => array
		(
			'Field' => 'keywords',
			'Type' => 'text',
			'Null' => 'YES',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'lft' => array
		(
			'Field' => 'lft',
			'Type' => 'int(10) unsigned',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'rgt' => array
		(
			'Field' => 'rgt',
			'Type' => 'int(10) unsigned',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'root_id' => array
		(
			'Field' => 'root_id',
			'Type' => 'int(10) unsigned',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'parent_id' => array
		(
			'Field' => 'parent_id',
			'Type' => 'int(11) unsigned',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'set_ignore' => array
		(
			'Field' => 'set_ignore',
			'Type' => 'tinyint(1)',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'template_name' => array
		(
			'Field' => 'template_name',
			'Type' => 'varchar(255)',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'sys_trashcan' => array
		(
			'Field' => 'sys_trashcan',
			'Type' => 'smallint(1) unsigned',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'sys_date_created' => array
		(
			'Field' => 'sys_date_created',
			'Type' => 'int(10) unsigned',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'sys_date_changed' => array
		(
			'Field' => 'sys_date_changed',
			'Type' => 'int(10) unsigned',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'cookie_name' => array
		(
			'Field' => 'cookie_name',
			'Type' => 'varchar(255)',
			'Null' => 'YES',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'cookie_lifetime' => array
		(
			'Field' => 'cookie_lifetime',
			'Type' => 'int(11)',
			'Null' => 'YES',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'cookie_value' => array
		(
			'Field' => 'cookie_value',
			'Type' => 'varchar(255)',
			'Null' => 'YES',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'redirect_to' => array
		(
			'Field' => 'redirect_to',
			'Type' => 'int(11)',
			'Null' => 'YES',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'structure' => array
		(
			'Field' => 'structure',
			'Type' => 'text',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'rights' => array
		(
			'Field' => 'rights',
			'Type' => 'int(10) unsigned',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
		'lost_mods' => array
		(
			'Field' => 'lost_mods',
			'Type' => 'text',
			'Null' => 'NO',
			'Key' => '',
			'Default' => NULL,
			'Extra' => '',
		),
	),
	'keys' => array
	(
		'0' => array
		(
			'type' => 'PRIMARY KEY',
			'fields' => array
			(
				'0' => 'id',
			),
		),
	),
	'data' => array
	(
		'0' => array
		(
			'id' => '1',
			'name' => 'tajapa',
			'url' => 'index.html',
			'title' => '',
			'description' => '',
			'keywords' => '',
			'lft' => '1',
			'rgt' => '18',
			'root_id' => '1',
			'parent_id' => '0',
			'set_ignore' => '0',
			'template_name' => 'tajapa.php',
			'sys_trashcan' => '0',
			'sys_date_created' => '0',
			'sys_date_changed' => '0',
			'cookie_name' => '',
			'cookie_lifetime' => '0',
			'cookie_value' => '',
			'redirect_to' => '0',
			'structure' => 'b:0;',
			'rights' => '0',
			'lost_mods' => '',
		),
		'1' => array
		(
			'id' => '2',
			'name' => 'open',
			'url' => 'open.html',
			'title' => 'tajapa',
			'description' => 'tajapa',
			'keywords' => '',
			'lft' => '2',
			'rgt' => '3',
			'root_id' => '1',
			'parent_id' => '1',
			'set_ignore' => '0',
			'template_name' => 'tajapa_marketplace_open.php',
			'sys_trashcan' => '0',
			'sys_date_created' => '0',
			'sys_date_changed' => '0',
			'cookie_name' => '',
			'cookie_lifetime' => '0',
			'cookie_value' => '',
			'redirect_to' => '0',
			'structure' => 'b:0;',
			'rights' => '0',
			'lost_mods' => '',
		),
		'2' => array
		(
			'id' => '3',
			'name' => 'find',
			'url' => 'find.html',
			'title' => 'tajapa',
			'description' => 'tajapa',
			'keywords' => '',
			'lft' => '4',
			'rgt' => '5',
			'root_id' => '1',
			'parent_id' => '1',
			'set_ignore' => '0',
			'template_name' => 'tajapa_marketplace_find.php',
			'sys_trashcan' => '0',
			'sys_date_created' => '0',
			'sys_date_changed' => '0',
			'cookie_name' => '',
			'cookie_lifetime' => '0',
			'cookie_value' => '',
			'redirect_to' => '0',
			'structure' => 'b:0;',
			'rights' => '0',
			'lost_mods' => '',
		),
		'3' => array
		(
			'id' => '4',
			'name' => 'marketplace',
			'url' => 'marketplace.html',
			'title' => 'marketplace',
			'description' => 'marketplace',
			'keywords' => '',
			'lft' => '6',
			'rgt' => '7',
			'root_id' => '1',
			'parent_id' => '1',
			'set_ignore' => '0',
			'template_name' => 'tajapa_marketplace.php',
			'sys_trashcan' => '0',
			'sys_date_created' => '0',
			'sys_date_changed' => '0',
			'cookie_name' => '',
			'cookie_lifetime' => '0',
			'cookie_value' => '',
			'redirect_to' => '0',
			'structure' => 'b:0;',
			'rights' => '0',
			'lost_mods' => '',
		),
		'4' => array
		(
			'id' => '5',
			'name' => 'my requests',
			'url' => 'my_requests.html',
			'title' => 'my requests',
			'description' => 'my requests',
			'keywords' => '',
			'lft' => '8',
			'rgt' => '9',
			'root_id' => '1',
			'parent_id' => '1',
			'set_ignore' => '0',
			'template_name' => 'tajapa_my_requests.php',
			'sys_trashcan' => '0',
			'sys_date_created' => '0',
			'sys_date_changed' => '0',
			'cookie_name' => '',
			'cookie_lifetime' => '0',
			'cookie_value' => '',
			'redirect_to' => '0',
			'structure' => 'b:0;',
			'rights' => '0',
			'lost_mods' => '',
		),
		'5' => array
		(
			'id' => '6',
			'name' => 'my offers',
			'url' => 'my_offers.html',
			'title' => 'my offers',
			'description' => 'my offers',
			'keywords' => '',
			'lft' => '10',
			'rgt' => '11',
			'root_id' => '1',
			'parent_id' => '1',
			'set_ignore' => '0',
			'template_name' => 'tajapa_my_offers.php',
			'sys_trashcan' => '0',
			'sys_date_created' => '0',
			'sys_date_changed' => '0',
			'cookie_name' => '',
			'cookie_lifetime' => '0',
			'cookie_value' => '',
			'redirect_to' => '0',
			'structure' => 'b:0;',
			'rights' => '0',
			'lost_mods' => '',
		),
		'6' => array
		(
			'id' => '7',
			'name' => 'my transactions',
			'url' => 'my_transactions.html',
			'title' => 'my transactions',
			'description' => 'my transactions',
			'keywords' => '',
			'lft' => '12',
			'rgt' => '13',
			'root_id' => '1',
			'parent_id' => '1',
			'set_ignore' => '0',
			'template_name' => 'tajapa_my_transactions.php',
			'sys_trashcan' => '0',
			'sys_date_created' => '0',
			'sys_date_changed' => '0',
			'cookie_name' => '',
			'cookie_lifetime' => '0',
			'cookie_value' => '',
			'redirect_to' => '0',
			'structure' => 'b:0;',
			'rights' => '0',
			'lost_mods' => '',
		),
		'7' => array
		(
			'id' => '8',
			'name' => 'register',
			'url' => 'register.html',
			'title' => 'register',
			'description' => 'register',
			'keywords' => '',
			'lft' => '14',
			'rgt' => '15',
			'root_id' => '1',
			'parent_id' => '1',
			'set_ignore' => '0',
			'template_name' => 'tajapa_register.php',
			'sys_trashcan' => '0',
			'sys_date_created' => '0',
			'sys_date_changed' => '0',
			'cookie_name' => '',
			'cookie_lifetime' => '0',
			'cookie_value' => '',
			'redirect_to' => '0',
			'structure' => 'b:0;',
			'rights' => '0',
			'lost_mods' => '',
		),
		'8' => array
		(
			'id' => '9',
			'name' => 'my messages',
			'url' => 'my_messages.html',
			'title' => 'my messages',
			'description' => 'my messages',
			'keywords' => '',
			'lft' => '16',
			'rgt' => '17',
			'root_id' => '1',
			'parent_id' => '1',
			'set_ignore' => '0',
			'template_name' => 'tajapa_messaging.php',
			'sys_trashcan' => '0',
			'sys_date_created' => '0',
			'sys_date_changed' => '0',
			'cookie_name' => '',
			'cookie_lifetime' => '0',
			'cookie_value' => '',
			'redirect_to' => '0',
			'structure' => 'b:0;',
			'rights' => '0',
			'lost_mods' => '',
		),
	),

);
?>